#!/usr/bin/env bash
set -e

mkdir -p lib/

# arg0: Output path.
# arg1: Command for downloading
try_fetch() {
    if [[ -d $2 ]]
    then
        echo "try_fetch: Skipping $2: already exists"
    else
        ${@:1}
    fi
}

fetch() {
    try_fetch "git clone https://github.com/limine-bootloader/limine.git --branch=v5.x-branch-binary --depth=1" "stand/limine"
    try_fetch "git clone https://github.com/sigsegv7/hyra-mlibc lib/mlibc"
}

build_limine() {
    make -C stand/limine/
}

init_mlibc() {
	cp builddeps/cross_file.txt lib/mlibc/
}

build() {
    build_limine
    init_mlibc
}

echo "----------------------------------"
echo
echo "      Fetching sources...        "
echo
echo "----------------------------------"
echo -e "\n"

fetch           # Fetch sources

echo "----------------------------------"
echo
echo "      Building sources...        "
echo
echo "----------------------------------"
echo -e "\n"

build           # Build sources

if [[ ! -f ./configure ]]
then
    echo "Creating configure script..."
    autoconf
fi
