#!/bin/bash

set -e

ip tuntap add dev tap0 mode tap
ip link set tap0 up
echo "mktap: tap0 is UP"

ip link add name br0 type bridge
ip addr add 192.168.100.1/24 dev br0
ip link set br0 up
ip link set tap0 master br0
echo "mktap: tap0 master br0"
