#!/bin/bash
#
# To be ran during the build process to export
# system headers
#

TARGET_DIR=lib/libc/include/sys
SYS_DIR=../../../../sys/include/sys

if [ -f $TARGET_DIR/.sys_export ]
then
    exit 0
fi

. builddeps/sysexports

echo "Exporting sys headers..."
cd $TARGET_DIR

for i in $sys_headers
do
    if [ -s "$i" ]
    then
        echo "HEADER CONFLICT ($TARGET_DIR/$i)"
        continue
    fi

    echo "sys/include/sys/$i -> lib/libc/include/sys/$i"
    echo include/sys/$i >>.sys_export
    echo "$i" >>.gitignore
    ln -sf $SYS_DIR/$i .
done
